---

# File: dstar-deploy-playbook.yml
# Author: Bryan Jurish <jurish@bbaw.de>
# Description: deploy new forkutils on dstar-all hosts
# Usage:
#  ansible-playbook -K -i ~/dstar/admin/hosts dstar-deploy-playbook.yml -e 'hosts=dstar-all'

- name: deploy forkutils on selected hosts (default=dstar-all)
  #gather_facts: false
  #hosts: www.dwds.de
  #hosts: dstar-all
  hosts: "{{ hosts | default('dstar-all') }}"
  connection: ssh
  vars:
    hosts: dstar-all

  tasks:

    - name: svn update
      shell: svn up dstar/cabx/forkutils #-- expect warnings

    - name: build
      shell: perl Makefile.PL </dev/null && make && make test
      args:
        chdir: /home/ddc-dstar/dstar/cabx/forkutils

    - name: install
      become: true
      become_user: root
      become_method: sudo
      shell: make install
      args:
        chdir: /home/ddc-dstar/dstar/cabx/forkutils
